/* ============ Catculator — textos en español e inglés ============

   Se carga ANTES que renderer.js. Deja dos globales: TEXTOS y IDIOMAS.

   Reglas al añadir textos:
   - Toda clave que exista en 'es' tiene que existir en 'en'. Hay una prueba
     (npm test) que falla si falta alguna, en cualquiera de los dos sentidos.
   - Los arreglos son frases que el gato dice al azar. Pueden tener distinta
     cantidad en cada idioma: no se emparejan por índice.
   - {n}, {a}, {b} se sustituyen por valores al llamar a t().
   - Los emojis van dentro del texto porque a veces cambian de posición según
     el idioma.

   Sobre traducir a un gato: los chistes no se traducen literal, se reescriben.
   "Miaugnífico" no es "Meownificent" palabra por palabra, pero cumple la misma
   función. Donde el español juega con "gato", el inglés juega con "purr",
   "meow" y "claw". */

const IDIOMAS = ['es', 'en'];

const TEXTOS = {
  es: {
    // ---------- Barra superior ----------
    'top.historial': 'Historial',
    'top.conversor': 'Conversor de unidades',
    'top.aprendiz': 'Modo aprendiz',
    'top.sonido': 'Sonido',
    'top.idioma': 'Cambiar idioma',
    'top.personalizar': 'Cambiar color',
    'top.personalizar.aria': 'Personalizar color, pelaje y atuendo',

    // ---------- Pantalla ----------
    'frac.title': 'Ver como fracción / decimal',
    'frac.aria': 'Ver como fracción o decimal',
    'result.title': 'Tocar para copiar · mantener para pegar',
    'result.desc': 'Resultado. Enter para copiarlo. Con una cuenta a medias, tocar coloca el cursor y las flechas lo mueven.',
    'miau': '¡Miau!',

    // ---------- Controles ----------
    'ctrl.modo': 'Cambiar modo',
    'ctrl.cientifica': '🔬 Científica',
    'ctrl.basica': '🐱 Básica',
    'ctrl.notas': '📝 Notas',
    'ctrl.notas.title': 'Bloc de notas',
    'ctrl.compras': '🛒 Compras',
    'ctrl.compras.title': 'Modo compras',
    'ctrl.angulo': 'Grados / Radianes',
    'ctrl.memoria': 'Memoria activa',

    // ---------- Panel de personalización ----------
    'tema.titulo': 'Tema de color 🎨',
    'tema.cian': 'Cian',
    'tema.rosa': 'Rosa',
    'tema.menta': 'Menta',
    'tema.lavanda': 'Lavanda',
    'tema.atigrado': 'Atigrado',
    'tema.noche': 'Noche',
    'pelaje.titulo': 'Tu pelaje 🐱',
    'pelaje.carbon': 'Carbón',
    'pelaje.naranja': 'Naranja',
    'pelaje.gris': 'Gris',
    'pelaje.negro': 'Negro',
    'pelaje.blanco': 'Blanco',
    'pelaje.leon': 'León',
    'pelaje.tigre': 'Tigre',
    'pelaje.leopardo': 'Leopardo',
    'pelaje.jaguar': 'Jaguar',
    'pelaje.guepardo': 'Guepardo',
    'pelaje.nieves': 'Leopardo de las nieves',
    'especie.titulo': 'Felinos salvajes 🦁',
    'atuendo.titulo': 'Tu atuendo 🎩',
    'atuendo.ninguno': 'Ninguno',
    'atuendo.ninja': 'Ninja',
    'atuendo.futbol': 'Futbolero',
    'atuendo.pirata': 'Pirata',
    'atuendo.mago': 'Mago',
    'atuendo.capucha': 'Encapuchado',

    'ajustes.titulo': 'Ajustes ⚙️',
    'ajustes.vibrar': 'Vibrar al pulsar 📳',

    // ---------- Historial ----------
    'hist.titulo': 'Historial 🕘',
    'hist.borrar': 'Borrar historial 🧽',
    'hist.vacio': 'Aún no hay cuentas... ¡a calcular! 🐾',
    'hist.usar': 'Usar este resultado',

    // ---------- Conversor de unidades ----------
    'conv.titulo': 'Conversor de unidades ⇄',
    'conv.tipo': 'Tipo de unidad',
    'conv.numero': 'Número a convertir',
    'conv.origen': 'Unidad de origen',
    'conv.destino': 'Unidad de destino',
    'conv.intercambiar': 'Intercambiar unidades',
    'conv.usar': 'Usar en la calculadora 🐾',

    'cat.longitud': '📏 Longitud',
    'cat.peso': '⚖️ Peso',
    'cat.temperatura': '🌡️ Temperatura',
    'cat.volumen': '🧪 Volumen',
    'cat.velocidad': '🚀 Velocidad',

    'u.mm': 'mm', 'u.cm': 'cm', 'u.m': 'm', 'u.km': 'km',
    'u.in': 'pulgadas', 'u.ft': 'pies', 'u.yd': 'yardas', 'u.mi': 'millas',
    'u.mg': 'mg', 'u.g': 'g', 'u.kg': 'kg',
    'u.lb': 'libras', 'u.oz': 'onzas', 'u.t': 'toneladas',
    'u.ml': 'ml', 'u.l': 'litros', 'u.cup': 'tazas',
    'u.gal': 'galones (US)', 'u.floz': 'onzas líquidas',
    'u.ms': 'm/s', 'u.kmh': 'km/h', 'u.mph': 'mph', 'u.kn': 'nudos',

    // ---------- Bloc de notas ----------
    'notas.titulo': 'Bloc de notas 📝',
    'notas.aria': 'Bloc de notas',
    'notas.placeholder': 'Apunta aquí tus cuentas, listas o ideas... se guardan solas 🐾',
    'notas.insertar': '➕ Resultado',
    'notas.borrar': '🧽 Borrar',

    // ---------- Modo compras ----------
    'shop.titulo': 'Modo compras 🛒',
    'shop.precio': 'Precio',
    'shop.descuento': 'Descuento',
    'shop.descuento.aria': 'Descuento en por ciento',
    'shop.iva': 'IVA',
    'shop.iva.aria': 'IVA en por ciento',
    'shop.siniva': 'Sin IVA',
    'shop.propina': 'Propina',
    'shop.propina.aria': 'Propina en por ciento',
    'shop.entre': 'Entre',
    'shop.entre.aria': 'Entre cuántas personas',
    'shop.usar': 'Usar en la calculadora',
    'shop.divisa': 'Convertir divisa 💱',
    'shop.monto': 'Monto a convertir',
    'shop.moneda.de': 'Moneda del precio',
    'shop.moneda.a': 'Moneda a la que se convierte',
    'shop.moneda.a.title': 'Convertir a',
    'shop.intercambiar': 'Intercambiar monedas',
    'shop.nota': 'Escribe la tasa que conozcas (1 $ = ⋯). La app funciona sin internet, así que la actualizas tú. Toca el resultado para usarlo.',
    'shop.tasa.etiqueta': '1 $ =',
    'shop.tasa.aria': 'Cuántos {n} vale un dólar',
    'shop.cu': '{n} c/u',
    'shop.ivaparte': 'IVA {n}',

    // Antigüedad de las tasas
    'tasa.hoy': 'actualizada hoy',
    'tasa.dias': 'actualizada hace {n} días',
    'tasa.undia': 'actualizada ayer',
    'tasa.meses': 'actualizada hace {n} meses',
    'tasa.unmes': 'actualizada hace un mes',
    'tasa.nunca': 'sin actualizar desde {n}',

    'm.CRC': 'Colón', 'm.USD': 'Dólar', 'm.EUR': 'Euro',
    'm.MXN': 'Peso mexicano', 'm.CAD': 'Dólar canadiense',
    'm.BRL': 'Real brasileño', 'm.ARS': 'Peso argentino',
    'm.COP': 'Peso colombiano', 'm.CLP': 'Peso chileno',
    'm.PEN': 'Sol peruano', 'm.GTQ': 'Quetzal',

    // ---------- Teclado básico ----------
    'k.borrartodo': 'Borrar todo',
    'k.borrar': 'Borrar lo último',
    'k.porciento': 'por ciento',
    'k.dividir': 'dividir',
    'k.multiplicar': 'multiplicar',
    'k.restar': 'restar',
    'k.sumar': 'sumar',
    'k.signo': 'Cambiar signo',
    'k.punto': 'punto decimal',
    'k.coma': 'coma decimal',
    'k.igual': 'igual',

    // ---------- Teclado científico ----------
    's.mc': 'Memoria: borrar', 's.mr': 'Memoria: recuperar',
    's.mplus': 'Memoria: sumar', 's.mminus': 'Memoria: restar',
    's.ms': 'Memoria: guardar', 's.2nd': 'Segunda función',
    's.sin': 'seno', 's.asin': 'arcoseno',
    's.cos': 'coseno', 's.acos': 'arcocoseno',
    's.tan': 'tangente', 's.atan': 'arcotangente',
    's.pi': 'pi', 's.pow': 'x elevado a y',
    's.ln': 'logaritmo natural', 's.exp': 'e elevado a x',
    's.log': 'logaritmo base diez', 's.pow10': 'diez elevado a x',
    's.sqrt': 'raíz cuadrada', 's.cbrt': 'raíz cúbica',
    's.e': 'número e', 's.sq': 'x al cuadrado', 's.cube': 'x al cubo',
    's.abrir': 'abrir paréntesis', 's.cerrar': 'cerrar paréntesis',
    's.inv': 'uno entre x', 's.fact': 'factorial',
    's.abs': 'valor absoluto', 's.expn': 'exponente',
    's.mod': 'módulo', 's.ans': 'respuesta anterior',

    'pie': 'Hecho con 🐾 y mucho ronroneo',

    // ---------- Lo que dice el gato ----------
    'say.saludo': '¡Miau! Lista para calcular 🐾',
    'say.copiado': '¡Copiado en mis patitas! 📋',
    'say.dormir': 'Zzz... 💤',
    'say.despertar': '¡Miau! ¿En qué estábamos? 🐱',
    'say.pi': 'Mmm... ¡pi! ¿Pastel de atún? 🥧',
    'say.nueva': '¡Hay una versión nueva! Recarga para estrenarla ✨',
    'say.limpiar': ['¡Borrón y gato nuevo! 🐱', 'Limpio como mis bigotes ✨', '¡Listo para cazar números!'],

    'say.error': ['¡Miau! Eso no computa 🙀', 'Ni con nueve vidas resuelvo eso 😿', '¡Error gatuno! Revisa la operación 🐾'],
    'say.error.div0': '¡MIAU! ¡Entre cero NO, humano! 😾',

    'say.nueve': '¡9! Como mis vidas 🐾',
    'say.42': 'La respuesta a todo... y al atún 🐟',
    'say.666': 'Numeritos de gato negro 🐈‍⬛',
    'say.cero': 'Cero... como los ratones que cacé hoy 😿',
    'say.grande': '¡MIAU! ¡Qué número tan gatormemente grande! 🙀',
    'say.bien': ['¡Purrfecto! 😺', '¡Miaugnífico!', '*ronroneo de aprobación*', '¡Ni un ratón lo calcula mejor!', '¡Eso fue gatástico! 🐾', 'Las cuentas claras y el atún espeso 🐟'],

    'say.sonido.on': '¡Miau! Sonido activado 🔊',
    'say.sonido.off': 'Modo sigiloso, como buen gato 🤫',
    'say.vibrar.on': 'Vibración activada 📳',
    'say.vibrar.off': 'Sin vibración: patitas suaves 🐾',
    'say.pegado': '¡Pegado! 📋',
    'say.pegar.no': 'Eso no me parece un número 🤔',
    'say.pegar.permiso': 'No me dejan mirar el portapapeles 🙀',
    'say.mem.borrada': 'Memoria borrada 🧽',
    'say.mem.guardada': 'Guardado en memoria 📥',
    'say.mem.sumada': 'Sumado a memoria ➕',
    'say.mem.restada': 'Restado de memoria ➖',

    'say.hist.usado': 'Recuperado del baúl de cuentas 🕘',
    'say.hist.borrado': 'Historial borradito, como platito de atún 🧽',
    'say.conv.usado': '¡Convertido y en pantalla! ⇄',
    'say.shop.usado': '¡Cuentas claras, atún espeso! 🛒',
    'say.shop.abrir': ['¡A cuidar las monedas! 🛒', 'Ni un colón de más, humano 🪙', 'Yo cazo ratones, tú cazas ofertas 🛒'],
    'say.notas.abrir': ['Apunta tú, que yo no tengo pulgares 📝', 'Tu bloc de notas gatuno 🐾', 'Ideas frescas como el atún 📝'],
    'say.notas.borrado': 'Bloc limpio como mis bigotes ✨',

    'say.quiz.inicio': '¡Modo aprendiz! Resuelve mi cuenta 🎓',
    'say.quiz.record': ' Récord: {n} 🔥',
    'say.quiz.bien': ['¡Correcto! 😺', '¡Purrfecto! 🐾', '¡Genio gatuno! 🎓', '¡Esa patita sabe! ✏️'],
    'say.quiz.nuevorecord': '¡Récord nuevo! 🔥{n} seguidas 🏆',
    'say.quiz.mal': 'Mmm no... {a} = {b} 😿',
    'say.quiz.fin': 'Fin de la clase. ¡Miau-tástico! 🎓',
    'say.quiz.nonumero': 'Eso no parece un número 🙀',

    'say.frac': ['¡En fracción y simplificada! 🐾', 'Partido en pedacitos, como mi atún 🐟', '¡Fracción purrfecta! 😺'],
    'say.ronroneo': ['Prrrrrr... 😌', '*ronroneo feliz*', 'Prrrr... sigue, humano 🐾', '*motor de ronroneos encendido*'],
    'say.miau': ['¡Miau! 😺', '¿Me trajiste atún? 🐟', '¡Cuidado con mis bigotes!', 'Soy la mejor CATculadora del mundo 🐾'],

    'say.tema.cian': '¡Cian, mi favorito! 💙',
    'say.tema.rosa': '¡Rosa purrincesa! 💗',
    'say.tema.menta': '¡Menta fresca! 💚',
    'say.tema.lavanda': '¡Lavanda relajante! 💜',
    'say.tema.atigrado': '¡Naranja atigrado! 🧡',
    'say.tema.noche': 'Modo gato nocturno 🌙',

    'say.pelaje.carbon': '¡Mi pelaje de siempre! 🐱',
    'say.pelaje.naranja': '¡Naranja! ¿Hay lasaña? 🧡',
    'say.pelaje.gris': '¡Gris elegante, casi azul ruso! 🐭',
    'say.pelaje.negro': '¡Gato negro, suerte para ti! 🐈‍⬛',
    'say.pelaje.blanco': '¡Blanco como la leche! 🥛',
    'say.pelaje.leon': '¡ROAAAR! Rey de la selva y de las sumas 🦁',
    'say.pelaje.tigre': '¡GRRRAAA! Rayas para sumar, garras para restar 🐯',
    'say.pelaje.leopardo': '¡Rosetas huecas! Sé contar, y también trepar 🐆',
    'say.pelaje.jaguar': '¡Mis rosetas llevan punto dentro! Mordida de campeón 🐆',
    'say.pelaje.guepardo': '¡El más rápido del mundo… y no sé rugir! Maúllo 🐆',
    'say.pelaje.nieves': '¡Del Himalaya! Tampoco rujo: yo resoplo ❄️',

    'say.atuendo.ninguno': 'Al natural, como buen gato 🐱',
    'say.atuendo.ninja': '¡Ninja! Silencioso como patita en alfombra 🥷',
    'say.atuendo.futbol': '¡GOOOL! Bueno, primero las cuentas ⚽',
    'say.atuendo.pirata': '¡Arrr! El terror de los siete sofás 🏴‍☠️',
    'say.atuendo.mago': '¡Abracadabra! Tus errores desaparecen 🧙',
    'say.atuendo.capucha': 'Nada es verdadero... todo es calculable 🤍',
    'say.idioma': '¡Ahora hablo español! 🌎'
  },

  en: {
    'top.historial': 'History',
    'top.conversor': 'Unit converter',
    'top.aprendiz': 'Study mode',
    'top.sonido': 'Sound',
    'top.idioma': 'Change language',
    'top.personalizar': 'Change colour',
    'top.personalizar.aria': 'Customise colour, coat and outfit',

    'frac.title': 'Show as fraction / decimal',
    'frac.aria': 'Show as fraction or decimal',
    'result.title': 'Tap to copy · hold to paste',
    'result.desc': 'Result. Press Enter to copy it. While typing a sum, tapping places the cursor and the arrow keys move it.',
    'miau': 'Meow!',

    'ctrl.modo': 'Switch mode',
    'ctrl.cientifica': '🔬 Scientific',
    'ctrl.basica': '🐱 Basic',
    'ctrl.notas': '📝 Notes',
    'ctrl.notas.title': 'Notepad',
    'ctrl.compras': '🛒 Shopping',
    'ctrl.compras.title': 'Shopping mode',
    'ctrl.angulo': 'Degrees / Radians',
    'ctrl.memoria': 'Memory in use',

    'tema.titulo': 'Colour theme 🎨',
    'tema.cian': 'Cyan',
    'tema.rosa': 'Pink',
    'tema.menta': 'Mint',
    'tema.lavanda': 'Lavender',
    'tema.atigrado': 'Tabby',
    'tema.noche': 'Night',
    'pelaje.titulo': 'Your coat 🐱',
    'pelaje.carbon': 'Charcoal',
    'pelaje.naranja': 'Ginger',
    'pelaje.gris': 'Grey',
    'pelaje.negro': 'Black',
    'pelaje.blanco': 'White',
    'pelaje.leon': 'Lion',
    'pelaje.tigre': 'Tiger',
    'pelaje.leopardo': 'Leopard',
    'pelaje.jaguar': 'Jaguar',
    'pelaje.guepardo': 'Cheetah',
    'pelaje.nieves': 'Snow leopard',
    'especie.titulo': 'Wild cats 🦁',
    'atuendo.titulo': 'Your outfit 🎩',
    'atuendo.ninguno': 'None',
    'atuendo.ninja': 'Ninja',
    'atuendo.futbol': 'Footballer',
    'atuendo.pirata': 'Pirate',
    'atuendo.mago': 'Wizard',
    'atuendo.capucha': 'Hooded',

    'ajustes.titulo': 'Settings ⚙️',
    'ajustes.vibrar': 'Vibrate on tap 📳',

    'hist.titulo': 'History 🕘',
    'hist.borrar': 'Clear history 🧽',
    'hist.vacio': 'No sums yet... let us calculate! 🐾',
    'hist.usar': 'Use this result',

    'conv.titulo': 'Unit converter ⇄',
    'conv.tipo': 'Unit type',
    'conv.numero': 'Number to convert',
    'conv.origen': 'Convert from',
    'conv.destino': 'Convert to',
    'conv.intercambiar': 'Swap units',
    'conv.usar': 'Use in the calculator 🐾',

    'cat.longitud': '📏 Length',
    'cat.peso': '⚖️ Weight',
    'cat.temperatura': '🌡️ Temperature',
    'cat.volumen': '🧪 Volume',
    'cat.velocidad': '🚀 Speed',

    'u.mm': 'mm', 'u.cm': 'cm', 'u.m': 'm', 'u.km': 'km',
    'u.in': 'inches', 'u.ft': 'feet', 'u.yd': 'yards', 'u.mi': 'miles',
    'u.mg': 'mg', 'u.g': 'g', 'u.kg': 'kg',
    'u.lb': 'pounds', 'u.oz': 'ounces', 'u.t': 'tonnes',
    'u.ml': 'ml', 'u.l': 'liters', 'u.cup': 'cups',
    'u.gal': 'gallons (US)', 'u.floz': 'fluid ounces',
    'u.ms': 'm/s', 'u.kmh': 'km/h', 'u.mph': 'mph', 'u.kn': 'knots',

    'notas.titulo': 'Notepad 📝',
    'notas.aria': 'Notepad',
    'notas.placeholder': 'Jot down sums, lists or ideas here... they save themselves 🐾',
    'notas.insertar': '➕ Result',
    'notas.borrar': '🧽 Clear',

    'shop.titulo': 'Shopping mode 🛒',
    'shop.precio': 'Price',
    'shop.descuento': 'Discount',
    'shop.descuento.aria': 'Discount in per cent',
    'shop.iva': 'VAT',
    'shop.iva.aria': 'VAT in per cent',
    'shop.siniva': 'Without VAT',
    'shop.propina': 'Tip',
    'shop.propina.aria': 'Tip in per cent',
    'shop.entre': 'Split by',
    'shop.entre.aria': 'How many people to split between',
    'shop.usar': 'Use in the calculator',
    'shop.divisa': 'Convert currency 💱',
    'shop.monto': 'Amount to convert',
    'shop.moneda.de': 'Currency of the price',
    'shop.moneda.a': 'Currency to convert to',
    'shop.moneda.a.title': 'Convert to',
    'shop.intercambiar': 'Swap currencies',
    'shop.nota': 'Type in the rate you know (1 $ = ⋯). The app works offline, so you keep it up to date. Tap a result to use it.',
    'shop.tasa.etiqueta': '1 $ =',
    'shop.tasa.aria': 'How many {n} one dollar is worth',
    'shop.cu': '{n} each',
    'shop.ivaparte': 'VAT {n}',

    'tasa.hoy': 'updated today',
    'tasa.dias': 'updated {n} days ago',
    'tasa.undia': 'updated yesterday',
    'tasa.meses': 'updated {n} months ago',
    'tasa.unmes': 'updated a month ago',
    'tasa.nunca': 'not updated since {n}',

    'm.CRC': 'Colón', 'm.USD': 'Dollar', 'm.EUR': 'Euro',
    'm.MXN': 'Mexican peso', 'm.CAD': 'Canadian dollar',
    'm.BRL': 'Brazilian real', 'm.ARS': 'Argentine peso',
    'm.COP': 'Colombian peso', 'm.CLP': 'Chilean peso',
    'm.PEN': 'Peruvian sol', 'm.GTQ': 'Quetzal',

    'k.borrartodo': 'Clear all',
    'k.borrar': 'Delete last',
    'k.porciento': 'per cent',
    'k.dividir': 'divide',
    'k.multiplicar': 'multiply',
    'k.restar': 'subtract',
    'k.sumar': 'add',
    'k.signo': 'Change sign',
    'k.punto': 'decimal point',
    'k.coma': 'decimal comma',
    'k.igual': 'equals',

    's.mc': 'Memory: clear', 's.mr': 'Memory: recall',
    's.mplus': 'Memory: add', 's.mminus': 'Memory: subtract',
    's.ms': 'Memory: store', 's.2nd': 'Second function',
    's.sin': 'sine', 's.asin': 'arcsine',
    's.cos': 'cosine', 's.acos': 'arccosine',
    's.tan': 'tangent', 's.atan': 'arctangent',
    's.pi': 'pi', 's.pow': 'x to the power of y',
    's.ln': 'natural logarithm', 's.exp': 'e to the power of x',
    's.log': 'base ten logarithm', 's.pow10': 'ten to the power of x',
    's.sqrt': 'square root', 's.cbrt': 'cube root',
    's.e': 'number e', 's.sq': 'x squared', 's.cube': 'x cubed',
    's.abrir': 'open bracket', 's.cerrar': 'close bracket',
    's.inv': 'one over x', 's.fact': 'factorial',
    's.abs': 'absolute value', 's.expn': 'exponent',
    's.mod': 'modulo', 's.ans': 'previous answer',

    'pie': 'Made with 🐾 and a lot of purring',

    'say.saludo': 'Meow! Ready to calculate 🐾',
    'say.copiado': 'Copied into my paws! 📋',
    'say.dormir': 'Zzz... 💤',
    'say.despertar': 'Meow! Where were we? 🐱',
    'say.pi': 'Mmm... pi! Is there tuna pie? 🥧',
    'say.nueva': 'There is a new version! Reload to try it ✨',
    'say.limpiar': ['Clean slate, fresh cat! 🐱', 'Clean as my whiskers ✨', 'Ready to hunt some numbers!'],

    'say.error': ['Meow! That does not compute 🙀', 'Not even nine lives could solve that 😿', 'Cat-astrophic error! Check the sum 🐾'],
    'say.error.div0': 'MEOW! Not by zero, human! 😾',

    'say.nueve': '9! Just like my lives 🐾',
    'say.42': 'The answer to everything... and to tuna 🐟',
    'say.666': 'Proper black cat numbers 🐈‍⬛',
    'say.cero': 'Zero... like the mice I caught today 😿',
    'say.grande': 'MEOW! That number is claw-fully big! 🙀',
    'say.bien': ['Purrfect! 😺', 'Meownificent!', '*purr of approval*', 'No mouse could do it better!', 'That was claw-some! 🐾', 'Numbers crunched, tuna served 🐟'],

    'say.sonido.on': 'Meow! Sound on 🔊',
    'say.sonido.off': 'Stealth mode, like a proper cat 🤫',
    'say.vibrar.on': 'Vibration on 📳',
    'say.vibrar.off': 'No vibration: soft paws 🐾',
    'say.pegado': 'Pasted! 📋',
    'say.pegar.no': "That doesn't look like a number 🤔",
    'say.pegar.permiso': 'They will not let me peek at the clipboard 🙀',
    'say.mem.borrada': 'Memory cleared 🧽',
    'say.mem.guardada': 'Stored in memory 📥',
    'say.mem.sumada': 'Added to memory ➕',
    'say.mem.restada': 'Subtracted from memory ➖',

    'say.hist.usado': 'Fished out of the number chest 🕘',
    'say.hist.borrado': 'History wiped clean, like a tuna plate 🧽',
    'say.conv.usado': 'Converted and on screen! ⇄',
    'say.shop.usado': 'Numbers crunched, tuna served! 🛒',
    'say.shop.abrir': ['Let us guard those coins! 🛒', 'Not a penny more, human 🪙', 'I hunt mice, you hunt bargains 🛒'],
    'say.notas.abrir': ['You write it down, I have no thumbs 📝', 'Your feline notepad 🐾', 'Ideas as fresh as tuna 📝'],
    'say.notas.borrado': 'Notepad clean as my whiskers ✨',

    'say.quiz.inicio': 'Study mode! Solve my sum 🎓',
    'say.quiz.record': ' Record: {n} 🔥',
    'say.quiz.bien': ['Correct! 😺', 'Purrfect! 🐾', 'Feline genius! 🎓', 'That paw knows its maths! ✏️'],
    'say.quiz.nuevorecord': 'New record! 🔥{n} in a row 🏆',
    'say.quiz.mal': 'Mmm no... {a} = {b} 😿',
    'say.quiz.fin': 'Class dismissed. Meow-tastic! 🎓',
    'say.quiz.nonumero': 'That does not look like a number 🙀',

    'say.frac': ['As a fraction, fully simplified! 🐾', 'Split into little pieces, like my tuna 🐟', 'Purrfect fraction! 😺'],
    'say.ronroneo': ['Prrrrrr... 😌', '*happy purring*', 'Prrrr... carry on, human 🐾', '*purr engine started*'],
    'say.miau': ['Meow! 😺', 'Did you bring tuna? 🐟', 'Mind the whiskers!', 'I am the best CATculator in the world 🐾'],

    'say.tema.cian': 'Cyan, my favourite! 💙',
    'say.tema.rosa': 'Purrincess pink! 💗',
    'say.tema.menta': 'Fresh mint! 💚',
    'say.tema.lavanda': 'Relaxing lavender! 💜',
    'say.tema.atigrado': 'Tabby orange! 🧡',
    'say.tema.noche': 'Night cat mode 🌙',

    'say.pelaje.carbon': 'My usual coat! 🐱',
    'say.pelaje.naranja': 'Ginger! Is there lasagna? 🧡',
    'say.pelaje.gris': 'Elegant grey, almost Russian Blue! 🐭',
    'say.pelaje.negro': 'Black cat, luck for you! 🐈‍⬛',
    'say.pelaje.blanco': 'White as milk! 🥛',
    'say.pelaje.leon': 'ROAAAR! King of the jungle and of sums 🦁',
    'say.pelaje.tigre': 'GRRRAAA! Stripes for adding, claws for subtracting 🐯',
    'say.pelaje.leopardo': 'Hollow rosettes! I can count, and climb too 🐆',
    'say.pelaje.jaguar': 'My rosettes have a dot inside! Champion bite 🐆',
    'say.pelaje.guepardo': 'Fastest in the world… and I cannot roar! I meow 🐆',
    'say.pelaje.nieves': 'From the Himalayas! I do not roar either: I chuff ❄️',

    'say.atuendo.ninguno': 'All natural, like a proper cat 🐱',
    'say.atuendo.ninja': 'Ninja! Silent as a paw on carpet 🥷',
    'say.atuendo.futbol': 'GOOOAL! Well, maths first ⚽',
    'say.atuendo.pirata': 'Arrr! Terror of the seven sofas 🏴‍☠️',
    'say.atuendo.mago': 'Abracadabra! Your mistakes vanish 🧙',
    'say.atuendo.capucha': 'Nothing is true... everything is calculable 🤍',
    'say.idioma': 'Now I speak English! 🌎'
  }
};
